config/routes.rb
Rails.application.routes.draw do
  resources :cars do
    resources :pictures
  end
  root 'cars#index'

end

app/models/car.rb
class Car < ActiveRecord::Base
  has_many :pictures, dependent: :destroy
  accepts_nested_attributes_for :pictures, allow_destroy: true
end

app/models/picture.rb
class Picture < ActiveRecord::Base
  belongs_to :car
  has_attached_file :photo, styles: { medium: "300x300>", thumb: "100x100>" }
  validates_attachment_content_type :photo, content_type: /\Aimage\/.*\Z/
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  def index
    @cars = Car.order(:id)
  end

  def new
    @car = Car.new

  end

  def edit
    @car = Car.find(params[:id])
  end

  def create
    @car = Car.new(car_params)
    if @car.save
      if params[:photos]
        params[:photos].each { |p| @car.pictures.create(photo: p)}
      end
      redirect_to '/'
    else
      render action: 'new'
    end
  end

  def update
    @car = Car.find(params[:id])
    @car.update(car_params)
    if params[:photos]
      params[:photos].each { |p| @car.pictures.create(photo: p)}
    end
    redirect_to '/'
  end

  def destroy
    @car = Car.find(params[:id])
    @car.destroy
    redirect_to '/'
  end

  private

    def car_params
      params.require(:car).permit(:name, :auto_number, :pts_number, :pts_date, pictures_attributes: [:photo])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/views/cars/_form.slim
.col-lg-10.col-lg-offset-0
  br
  = form_for @car, :html => { multipart: true, class: 'form-inline'} do |f|
    fieldset
      .row
        .form-group
          .col-lg-3
            = f.text_field :name, placeholder: 'Наименование', class: 'form-control'

        .form-group
          .col-lg-3
            = f.text_field :auto_number, placeholder: 'Гос.номер', class: 'form-control'
      .row
        .form-group
          .col-lg-3
            = f.text_field :pts_number, placeholder: 'Номер ПТС', class: 'form-control'

        .form-group
          .col-lg-3
            = f.text_field :pts_date, placeholder: 'Дата ПТС', 'data-provide' => 'datepicker', class: 'datepicker', 'data-date-format' => 'yyyy/mm/dd', 'data-date-language' => 'ru'
      .row
        h3 Список Фотографий:
        .col-lg-10
          - @car.pictures.each do |picture|
            = image_tag picture.photo.url(:medium), style: "border: 1px solid black"
      hr
        .form-group

          = file_field_tag "photos[]", type: :file, multiple: true, class: 'col-lg-offset-1', accept: 'image/png, image/jpg, image/jpeg'
      hr
      .row
        .form-group
          .col-lg-12.col-lg-offset-3
            = f.submit class: 'btn btn-primary'
            =< link_to :back, cars_path, class: 'btn btn-default'

app/views/cars/edit.slim
h2 Редактировать автомобиль
= render 'cars/form'

app/views/cars/index.slim
h2 Список автомобилей
table.table.table-bordered.table-hover
  thead
    tr
      th = '#'
      th = 'Наименовние'
      th = 'Гос. номер'
      th = 'ПТС'
      th = 'Дата ПТС'
      th = 'Фото'
      th = link_to 'Новый', new_car_path, class: 'btn btn-success'

  tbody
    - @cars.each do |car|
      tr
        td = car.id
        td = car.name
        td = car.auto_number
        td = car.pts_number
        td = car.try(:pts_date).try(:strftime, '%d/%m/%Y')
        td = '*' unless car.pictures.empty?
        td
          = link_to 'Редактировать', edit_car_path(car), class: 'btn btn-info'
          = link_to 'Удалить', car_path(car), method: :delete, class: 'btn btn-danger', data: {confirm: 'Are you sure?'}
    td
      span Всего:
      =< @cars.count
    td colspan='6'

app/views/cars/new.slim
h2 Добавить новый автомобиль
= render 'cars/form'

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Cars</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>